<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Tous Les Films</title>
        <link href="CSS/style.css" rel="stylesheet" type="text/css">
        <!--<link href="../public/style.css" rel="stylesheet" type="text/css">-->
    </head>
    <body>
        
        <!--<script src="../public/JavaScript.js"></script>-->
        <div id="global">
            <header>
                <div id="bandeau">
                    <span class="titreSite">Tous Les Films</span>
                    <br />
                    <span class="slogan">Retrouvez les plaisirs!</span>
                </div>
                <span class="i_tel">Service Client: +33 12 34 56 78 90</span>
            </header>
            <nav>
                <ul id="menu">
                    <li><a href="/" title="Voir la page d'accueil">Accueil</a></li>
                    <li><a href="/show_all" title="Show all films">All Films</a></li>
                    <li><a href="/Ajouter" title="Ajouter un film">Ajouter</a></li>
                    <li><a href="/edit_film" title="Editer un film">Editer</a></li>
                    <li><a href="/delete_film" title="Supprimer un film">Supprimer</a></li>
                </ul>
                <ul id="slides">
                    <li class="slide showing"><a href="/show_all"><img src="images/Justice-League-pourquoi-Warner-DC-ne-doit-pas-se-planter.jpg" width="800" height="500" /></a></li>
                    <li class="slide"><a href="/show_all"><img src="images/Star-Wars-8-Les-Derniers-Jedi-affiche-definitive-2017-Gouaig.fr_.png" width="800" height="500" /></a></li>
                    <li class="slide"><a href="/show_all"><img src="images/MazingerZInfinity2-799x445.jpg" width="800" height="500" /></a></li>
                    <li class="slide"><a href="/show_all"><img src="images/kingsman-2-cercle-dor-best-promo-eclipse-et-nouvelle-affiche-une-631x250.jpg" width="800" height="500" /></a></li>
                    
                </ul>
                <button class="controls" id="pause">Pause</button>
                <button class="controls" id="previous">Previous</button>
                <button class="controls" id="next">Next</button>
                <script src="JavaScript/JavaScript.js"></script>
                
            </nav>
            <footer id="piedDePage">
                <a href="mailto:12456@example.com">Contactez-Nous</a>
            </footer>
            
            
        </div>
    </body>
</html>