<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Show All Films</title>
        <link href="style.css" rel="stylesheet" type="text/css">

        <!--<link href="../public/style.css" rel="stylesheet" type="text/css">--> 
    </head>
    <body>
    	
        <!--<script src="../public/JavaScript.js"></script>--> 
        <div id="global">
            <header>
        		<div id="bandeau">
        			<span class="titreSite">Tous Les Films</span>
        			<br />
        			<span class="slogan">Retrouvez les plaisirs!</span>
        		</div>


        		<span class="i_tel">Service Client: +33 12 34 56 78 90</span>
            </header>
            <nav>

                    <ul id="menu">
                        <li><a href="/" title="Voir la page d'accueil">Accueil</a></li>
                        <li><a href="/show_all" title="Show all films">All Films</a></li>
                        <li><a href="/Ajouter" title="Ajouter un film">Ajouter</a></li>
                        <li><a href="/edit_film" title="Editer un film">Editer</a></li>
                        <li><a href="/delete_film" title="Supprimer un film">Supprimer</a></li>
                    </ul>
                        
            </nav>
            <div>
                <p><img src="<?php echo $film->Image_lien?>" /></p>
                <br>
                <h1><?php echo $film->Titre;?></h1>
                <br>
                <h2>De <?php echo $film->Directeur; ?></h2>
                <br>
                <h2>Avec <?php echo $film->Acteur; ?></h2>
                <br>
                <p><?php echo $film->Synopsis; ?></p>
                <br>
                    
            </div>
            <footer id="piedDePage">
                <a href="mailto:12456@example.com">Contactez-Nous</a> 
            </footer>
            
            
        </div>

    </body>
</html>